---
abstract: 'Find Duplicate Perl Code'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  Test::Most: 0.25
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Code-CutNPaste
provides:
  B::CutNPaste:
    file: lib/B/CutNPaste.pm
    version: 0.20
  Code::CutNPaste:
    file: lib/Code/CutNPaste.pm
    version: 0.03
  Code::CutNPaste::Duplicate:
    file: lib/Code/CutNPaste/Duplicate.pm
    version: 0
  Code::CutNPaste::Duplicate::Item:
    file: lib/Code/CutNPaste/Duplicate/Item.pm
    version: 0
requires:
  Capture::Tiny: 0.17
  File::Find::Rule: 0.33
  File::HomeDir: 0
  File::Slurp: 9999.19
  Moo: 0
  Parallel::ForkManager: 0.007009
  Term::ProgressBar: 0
  aliased: 0
  autodie: 2.10
  perl: 5.006
  utf8::all: 0.004
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
